export default {
	text: {
		
		'2085-9': { //HDL
			text: "high density lipoprotein cholesterol",
			meaning: "Good cholesterol, bad cholesterol: what's the difference? Is there a 'naughty and nice' list for cholesterol? HDL cholesterol is the well-behaved 'good cholesterol.' This friendly scavenger cruises the bloodstream. As it does, it removes harmful bad cholesterol from where it doesn't belong. High HDL levels reduce the risk for heart disease -- but low levels increase the risk.",
			important: "People who have naturally higher levels of HDL cholesterol are at lower risk of heart attacks and stroke. However, it's less clear whether that same benefit holds true for people who increase their HDL levels with medications. Interventions known to increase HDL have shown to lower the risk of heart attacks, like exercise, quitting smoking or improving the diet. However, medications that specifically increase HDL have failed to reduce the rate of heart attacks.",
			improve: "If your HDL is low, you can take several steps to boost your HDL level and reduce your heart disease risk: i) Exercise: Aerobic exercise for 30 to 60 minutes on most days of the week can help pump up HDL. ii) Quit smoking: Tobacco smoke lowers HDL, and quitting can increase HDL levels. iii) Keep a healthy weight: Besides improving HDL levels, avoiding obesity reduces risk for heart disease and multiple other health conditions."
		},

		'2093-3': { //Cholesterol
			text: "cholesterol",
			meaning: "To understand high blood cholesterol (ko-LES-ter-ol), it helps to learn about cholesterol. Cholesterol is a waxy, fat-like substance that’s found in all cells of the body. Your body needs some cholesterol to make hormones, vitamin D, and substances that help you digest foods. Your body makes all the cholesterol it needs. However, cholesterol also is found in some of the foods you eat. Cholesterol travels through your bloodstream in small packages called lipoproteins (lip-o-PRO-teens). These packages are made of fat (lipid) on the inside and proteins on the outside. Two kinds of lipoproteins carry cholesterol throughout your body: low-density lipoproteins (LDL) and high-density lipoproteins (HDL). Having healthy levels of both types of lipoproteins is important. LDL cholesterol sometimes is called “bad” cholesterol. A high LDL level leads to a buildup of cholesterol in your arteries. (Arteries are blood vessels that carry blood from your heart to your body.) HDL cholesterol sometimes is called “good” cholesterol. This is because it carries cholesterol from other parts of your body back to your liver. Your liver removes the cholesterol from your body.",
			important: "People who have high blood cholesterol have a greater chance of getting coronary heart disease, also called coronary artery disease. (In this article, the term “heart disease” refers to coronary heart disease.) The higher the level of LDL cholesterol in your blood, the GREATER your chance is of getting heart disease. The higher the level of HDL cholesterol in your blood, the LOWER your chance is of getting heart disease. Coronary heart disease is a condition in which plaque (plak) builds up inside the coronary (heart) arteries. Plaque is made up of cholesterol, fat, calcium, and other substances found in the blood. When plaque builds up in the arteries, the condition is called atherosclerosis (ATH-er-o-skler-O-sis).",
			improve: "Lowering your cholesterol may slow, reduce, or even stop the buildup of plaque in your arteries. It also may reduce the risk of plaque rupturing and causing dangerous blood clots."
		},

		'8480-6': { //sysBP
			text: "systolic blood pressure",
			meaning: "When your heart beats, it pumps blood round your body to give it the energy and oxygen it needs. As the blood moves, it pushes against the sides of the blood vessels. The strength of this pushing is your blood pressure. If your blood pressure is too high, it puts extra strain on your arteries (and your heart) and this may lead to heart attacks and strokes. The first (or top) number is your systolic blood pressure. It is the highest level your blood pressure reaches when your heart beats. The second (or bottom) number is your diastolic blood pressure. It is the lowest level your blood pressure reaches as your heart relaxes between beats.",
			important: "We have discovered that systolic blood pressure (the top number or highest blood pressure when the heart is squeezing and pushing the blood round the body) is more important than diastolic blood pressure (the bottom number or lowest blood pressure between heart beats) because it gives the best idea of your risk of having a stroke or heart attack. We know, for example, that having a blood pressure of 160/80mmHg is more “risky” than having a blood pressure of 150/90mmHg. Having a raised systolic blood pressure but normal or low diastolic blood pressure is called Isolated Systolic Hypertension (ISH) and carries an increased risk of developing heart attacks or strokes and should be treated.",
			improve: "Eat a well-balanced, low-salt diet. Limit alcohol. Enjoy regular physical activity. Maintain a healthy weight. Take your medications properly."
		},

		'8462-4': { //diasBP
			text: "diastolic blood pressure",
			meaning: "When your heart beats, it pumps blood round your body to give it the energy and oxygen it needs. As the blood moves, it pushes against the sides of the blood vessels. The strength of this pushing is your blood pressure. If your blood pressure is too high, it puts extra strain on your arteries (and your heart) and this may lead to heart attacks and strokes. The first (or top) number is your systolic blood pressure. It is the highest level your blood pressure reaches when your heart beats. The second (or bottom) number is your diastolic blood pressure. It is the lowest level your blood pressure reaches as your heart relaxes between beats.",
			important: "However, there are some circumstances where diastolic blood pressure may be more important than systolic. For example, some studies suggest that, in people aged younger than 40 years, diastolic blood pressure is a better way of assessing risk. However, younger people are less likely to have a stroke or heart attack, so information on their risk of future problems is limited. It could be that diastolic blood pressure becomes more important when it is very high. There is some evidence to suggest that, for example, a blood pressure of 180/120mmHg gives a greater risk of stroke or heart attack than 180/100mmHg. The only way to resolve this issue is to obtain data from thousands of patients collected on a systematic basis. The statistical tests to investigate the relative importance of systolic and diastolic blood pressure are immensely complicated. However, current evidence strongly suggests that, over the age of 40, it is systolic pressure that is most important.",
			improve: "Eat a well-balanced, low-salt diet. Limit alcohol. Enjoy regular physical activity. Maintain a healthy weight. Take your medications properly."
		},
	}		
};